name: AppWars
version: '${project.version}'
main: dev.fluyd.appwars.AppWars
load: STARTUP
depend: [Citizens]
commands:
  buildmode:
    description: Toggles build mode
  test:
    description: Execute a test flow
  setspawn:
    description: Set the spawn location
  spawn:
    description: Teleport to the spawn point
    aliases:
      - "hub"
      - "lobby"
  loc:
    description: Set the location of an arena
    usage: /loc <1 | 2 | 3> <arena>
  start:
    description: Start a game
  addbutton:
    description: Add a button to an arena
    usage: /addbutton <arena>
  magicfloor:
    description: Add a magic floor to an arena
    usage: /magicfloor <arena>
  wtfthebutton:
    description: Tells you the coordinates of the button
    usage: /wtfthebutton
  cancel:
    description: Cancel the game
    usage: /cancel