name: AppWars
version: '${project.version}'
main: dev.fluyd.appwars.AppWars
load: STARTUP
commands:
  buildmode:
    description: Toggles build mode.
  test:
    description: Execute a test flow.
  setspawn:
    description: Set the spawn location
  spawn:
    description: Teleport to the spawn point
    aliases:
      - "hub"
      - "lobby"